wkdtpgns5016/webserve

CMakeLists.txt, webserve/TestExample/TestExample.test.cpp, webserve/lib/ft/ft.hpp, webserve/lib/ft/ft.test.cpp, webserve/lib/ft/splitBlockString.cpp, webserve/lib/ft/splitString.cpp
1. splitStirngTest 테스트 코드 구현
2. splitBlockTest 테스트 코드 구현
=> [Test] ft 라이브러리 테스트 코드 작성

docs/classSpecification.md, webserve/ServerParser/ServerParser.cpp, webserve/ServerParser/ServerParser.hpp
1. 틀, docs 수정
2. parsePort함수 추가
=> ServerParser 클래스추가

webserve/Makefile, webserve/Server/Server.cpp, webserve/Server/Server.hpp, webserve/ServerRun/ServerRun.cpp, webserve/ServerRun/ServerRun.hpp, webserve/WebServer/WebServer.cpp, webserve/WebServer/WebServer.hpp, webserve/main.cpp
1. Server 객체 생성
2. ServerRun 객체 생성
3. WebServer 객체 생성
resolved #12
=> [Feat] Server 객체 생성

webserve/ServerParser/ServerParser.cpp, webserve/ServerRun/ServerRun.cpp
1. ServerParser 객체 생성자 _port 초기값 80 변경
2. ServerRun 객체socket_init port 관련 조건문 삭제, 변경
Related to #16
=> [Feat] ServerParser.cpp ServerRun.cpp 일부 수정

CMakeLists.txt, webserve/LocationParser/LocationParser.cpp, webserve/LocationParser/LocationParser.hpp, webserve/LocationParser/LocationParser.test.cpp
=> [Merge] LocationParser 객체 구현

CMakeLists.txt, webserve/ServerParser/ServerParser.cpp, webserve/ServerParser/ServerParser.hpp, webserve/ServerParser/testServerParser.cpp
1. Addr함수 수정
2. Root관련 함수 추가
Related to #8
=> Feat: ServerParser Root관련 함수 추가 및 Addr함수 수정

CMakeLists.txt, docs/ClassDiagram/Diagram.drawio, var/conf/test.conf, webserve/Parser/Parser.cpp, webserve/Parser/Parser.hpp, webserve/Parser/Parser.test.cpp
=> Parser클래스 추가

webserve/Parser/Parser.cpp, webserve/Parser/Parser.hpp, webserve/Parser/Parser.test.cpp
1. extract함수를 jump함수들로 바꿈
2. extract함수들은 리턴값으로 문자열의 첫번째 위치, 마지막 위치를 페어로 리턴, jump함수들은 마지막 위치만 리턴
3. 테스트 파일 수정
Related to #25
=> Feat: Parser클래스 수정

Makefile, var/html/test.html, webserve/Server/Server.cpp, webserve/ServerHandler/ServerHandler.cpp, webserve/ServerHandler/ServerHandler.hpp
1. 적절한 경로를 반환하는 기능 추가
2. location block에 대한 redirect 기능 및 설정 찾는 기능 필요
Related to #14
=> [Feat] ServerHandler findPath 기능 추가

Makefile, var/conf/default.conf, var/conf/tester.conf, webserve/CommonLogFormat/CommonLogFormat.cpp, webserve/Configuration/ConfigDto/ConfigDto.cpp, webserve/Configuration/ConfigDto/ConfigDto.hpp, webserve/RequestHandler/DeleteHandler/DeleteHandler.cpp, webserve/RequestHandler/DeleteHandler/DeleteHandler.hpp, webserve/RequestHandler/GetHandler/GetHandler.cpp, webserve/RequestHandler/PostHandler/PostHandler.cpp, webserve/RequestHandler/PostHandler/PostHandler.hpp, webserve/RequestHandler/ServerHandler/ServerHandler.cpp, webserve/RequestHandler/ServerHandler/ServerHandler.hpp, webserve/ServerController/ServerController.cpp, webserve/lib/ft/ft.hpp, webserve/lib/ft/getTime.cpp
=> [Merge] Request Handler 기능 구현

webserve/Configuration/ServerBlock/ServerBlock.cpp, webserve/Configuration/config.test.cpp
=> Fix: url 파싱 오류 해결

CMakeLists.txt, webserve/Configuration/Block/Block.cpp, webserve/Configuration/Block/Block.hpp, webserve/Configuration/Parser/Parser.cpp, webserve/Configuration/Parser/Parser.hpp, webserve/Configuration/Scripter/Scripter.cpp, webserve/Configuration/Scripter/Scripter.hpp, webserve/Configuration/ServerBlock/ServerBlock.cpp
1. Block에서 간단지시어를 파싱하는 Parser, 읽고 원하는 단어를 리턴하는 Scripter 클래스를 따로 분리시킴
Related to #41
=> Refactor: Configuration 리펙토링

var/conf/tester.conf, var/html/error-page/40x.html, webserve/HttpMessage/HttpMessage.cpp, webserve/HttpMessage/HttpMessage.hpp, webserve/HttpMessage/HttpRequestMessage.cpp, webserve/HttpMessage/HttpResponseMessage.cpp, webserve/RequestHandler/DeleteHandler/DeleteHandler.cpp, webserve/RequestHandler/GetHandler/GetHandler.cpp, webserve/RequestHandler/PostHandler/PostHandler.cpp, webserve/RequestHandler/PutHandler/PutHandler.cpp, webserve/RequestHandler/ServerHandler/ServerHandler.cpp, webserve/RequestHandler/ServerHandler/ServerHandler.hpp, webserve/lib/ft/readFileIntoString.cpp
1. 요청 메세지 길이 초과 예외처리 구현
2. Default error page 설정 구현
=> [Feat] Http Handler 기능 구현

Makefile, var/html/a.html, webserve/Connection/Connection.cpp, webserve/Connection/Connection.hpp, webserve/HttpMessage/RequestMessageParser.cpp, webserve/HttpMessage/RequestMessageParser.hpp, webserve/Server/Server.cpp, webserve/Server/Server.hpp
1. 이미지, 미디어등 바이너리 파일 및 대용량 파일 업로드에 대한 http 메세지 파싱 기능 구현
resolved #57
=> [Feat] 대용량 파일 전송 처리 구현

CMakeLists.txt, Makefile, config_tester/Syntax/Id/ErrorArgument.conf, config_tester/Syntax/Id/ErrorContext.conf, config_tester/Syntax/Id/ErrorContext1.conf, config_tester/Syntax/Id/ErrorId.conf, config_tester/Syntax/Id/ErrorId1.conf, config_tester/Syntax/Id/default.conf, config_tester/excve.sh, webserve/Configuration/Block/Block.hpp, webserve/Configuration/Block/BlockException.cpp, webserve/Configuration/Block/BlockException.hpp, webserve/Configuration/Conf/Conf.cpp, webserve/Configuration/LocationBlock/LocationBlock.cpp, webserve/Configuration/Scripter/Scripter.cpp, webserve/Configuration/Scripter/Scripter.hpp, webserve/Configuration/ServerBlock/ServerBlock.cpp
1. 예외처리 클래스 추가
2. 테스트 케이스 추가
Related to #60
=> Fix: Block Id관련 유효성 검사 추가

Makefile, webserve/CGI/CGI.cpp, webserve/CGI/CGI.hpp, webserve/HttpMessage/HttpRequestMessage.cpp, webserve/HttpMessage/HttpRequestMessage.hpp, webserve/RequestHandler/ServerHandler/ServerHandler.cpp, webserve/RequestHandler/ServerHandler/ServerHandler.hpp
1. CGI env 설정 수정
Related to #65
=> [Feat] CGI env 설정 수정

test.cpp, test.py, var/html/cgi-bin/hello.pl, var/html/cgi-bin/multiple.py, webserve/CGI/CGI.cpp, webserve/CGI/CGI.hpp, webserve/HttpMessage/HttpRequestMessage.cpp, webserve/RequestHandler/DeleteHandler/DeleteHandler.cpp, webserve/RequestHandler/GetHandler/GetHandler.cpp, webserve/RequestHandler/PostHandler/PostHandler.cpp, webserve/RequestHandler/PutHandler/PutHandler.cpp, webserve/RequestHandler/ServerHandler/ServerHandler.cpp, webserve/RequestHandler/ServerHandler/ServerHandler.hpp
1. cgi 프로그램이 실행되도록 코드 수정
resolved #65
=> [Fix] cgi 객체 수정

a.out.dSYM/Contents/Info.plist, test.cpp, webserve/CGI/CGI.cpp
=> [Feat] CGI

var/html/YoupiBanane/directory/youpla.bla, webserve/CGI/CGI.cpp, webserve/Connection/Connection.cpp, webserve/HttpMessage/HttpMessage.cpp, webserve/HttpMessage/HttpMessage.hpp, webserve/RequestHandler/GetHandler/GetHandler.cpp, webserve/RequestHandler/PostHandler/PostHandler.cpp, webserve/RequestHandler/ServerHandler/ServerHandler.hpp
=> [Feat] ServerHandler CGI 처리

var/conf/tester.conf, webserve/Configuration/Block/Block.cpp, webserve/Configuration/ConfigDto/ConfigDto.cpp, webserve/Configuration/ConfigDto/ConfigDto.hpp, webserve/RequestHandler/ServerHandler/ServerHandler.cpp
1. ServerHandler 임시코드 제거
2. cgi-config 상속 안되는것 수정
resolved #86
=> [Fix] cgi-config에 따른 ServerHandler 수정

webserve/Buffer/Buffer.cpp, webserve/Buffer/Buffer.hpp, webserve/Connection/Connection.cpp, webserve/Connection/Connection.hpp, webserve/HttpMessage/HttpMessage.cpp, webserve/HttpMessage/HttpMessage.hpp, webserve/HttpMessage/HttpRequestMessage.cpp, webserve/HttpMessage/HttpRequestMessage.hpp, webserve/HttpMessage/HttpResponseMessage.cpp, webserve/HttpMessage/HttpResponseMessage.hpp, webserve/HttpMessage/RequestMessageParser.cpp, webserve/HttpMessage/RequestMessageParser.hpp, webserve/Log/Logger/Logger.cpp, webserve/Log/Logger/Logger.hpp, webserve/Server/Server.cpp, webserve/Server/Server.hpp
1. stirng const 레퍼런스화
2. server class 코드 리팩토링
resolved #98
=> [Fix] string const 레퍼런스화 및 기타 코드 리팩토링

webserve/RequestHandler/DeleteHandler/DeleteHandler.cpp, webserve/RequestHandler/GetHandler/GetHandler.cpp, webserve/RequestHandler/PostHandler/PostHandler.cpp, webserve/RequestHandler/PutHandler/PutHandler.cpp, webserve/RequestHandler/ServerHandler/ServerHandler.cpp, webserve/RequestHandler/ServerHandler/ServerHandler.hpp
1. 403에러클래스 추가
2. RequestHandler에 에러처리 파트 추가
Related to #106
=> Fix: 403에러 추가

webserve/main.cpp
1. 인자가 없을 경우 디폴트 path로 진행
2. file path가 잘못됐을 경우 예외처리 구현
resolved #119
=> [Fix] file path가 잘못됐을 경우 예외처리 수정

webserve/Connection/Connection.cpp
1. server_name 가상호스팅이 되지 않는 오류 수정
Related to #121
=> Fix: server_name 관련 오류 수정
